import { unzipSync, strFromU8 } from 'fflate';

const FCC_SOURCE = 'https://enterpriseefiling.fcc.gov/dataentry/api/download/dbfile/Current_LMS_Dump.zip';
const CACHE_PREFIX = 'fcc:transactions:';
const ALIASES = {
  call: ['callsign', 'call sign', 'station', 'station callsign', 'call_sign'], city: ['city', 'community', 'station city', 'community of license'], state: ['state', 'state code', 'state abbreviation'], service: ['service', 'service code', 'facility type', 'service type', 'app service'], file: ['file number', 'filenumber', 'application number', 'app number', 'id', 'file_no', 'application id'], type: ['purpose', 'transaction type', 'application purpose', 'form', 'application type', 'purpose description'], seller: ['assignor', 'seller', 'transferor', 'licensee'], buyer: ['assignee', 'buyer', 'transferee', 'applicant'], status: ['status', 'application status', 'status description'], filed: ['date filed', 'filed date', 'filing date', 'received date'], statusDate: ['status date', 'action date', 'date status', 'grant date', 'last action date']
};
function key(value) { return String(value ?? '').trim().toLowerCase().replace(/[^a-z0-9]/g, ''); }
function value(row, names) { const wanted = names.map(key); const found = Object.keys(row).find(k => wanted.includes(key(k))); return found ? String(row[found] ?? '').trim() : ''; }
function normalize(row, sourceFile) { const record = Object.fromEntries(Object.entries(ALIASES).map(([name, names]) => [name, value(row, names)])); record.source_file = sourceFile; record.review = !record.file || !record.call || !record.status || !record.statusDate; record.isTransaction = /assign|transfer|sale|control|renew|modif|permit|license|application|ownership/i.test(`${record.type} ${record.status}`); return record; }
function matchesService(row, service) { if (!service || service === 'all') return true; const text = row.service.toLowerCase(); if (service === 'television') return /tv|television|class ?a|lptv|dtv/.test(text); return /am|fm|radio|translator|lpfm/.test(text); }
function splitLine(line, delimiter) { const cells = []; let cell = ''; let quoted = false; for (let i = 0; i < line.length; i++) { const c = line[i], next = line[i + 1]; if (c === '"' && quoted && next === '"') { cell += '"'; i++; continue; } if (c === '"') { quoted = !quoted; continue; } if (c === delimiter && !quoted) { cells.push(cell); cell = ''; continue; } cell += c; } cells.push(cell); return cells; }
function parseDelimited(text, sourceFile) { const lines = text.replace(/^\uFEFF/, '').split(/\r?\n/).filter(line => line.trim()); if (lines.length < 2) return []; const sample = lines[0]; const delimiter = sample.includes('|') ? '|' : (sample.includes('\t') ? '\t' : ','); const headers = splitLine(lines[0], delimiter).map(header => header.trim()); if (!headers.some(header => /call|station|file|status|purpose|service/i.test(header))) return []; return lines.slice(1).map(line => { const cells = splitLine(line, delimiter); return Object.fromEntries(headers.map((header, index) => [header, cells[index] ?? ''])); }).map(row => normalize(row, sourceFile)); }
function extractRows(buffer) { const files = unzipSync(new Uint8Array(buffer)); const rows = []; for (const [name, bytes] of Object.entries(files)) { if (/\/|^_|readme|code.?table|schema/i.test(name) || bytes.length > 25_000_000) continue; const text = strFromU8(bytes); if (/\0/.test(text.slice(0, 2000))) continue; rows.push(...parseDelimited(text, name)); } const seen = new Set(); return rows.filter(row => { if (!row.isTransaction) return false; const identity = `${row.file}|${row.call}|${row.statusDate}|${row.type}`; if (seen.has(identity)) return false; seen.add(identity); return true; }); }
async function fetchDataset() { const upstream = await fetch(FCC_SOURCE, { cf: { cacheTtl: 86400, cacheEverything: true } }); if (!upstream.ok) throw new Error(`FCC LMS source returned HTTP ${upstream.status}`); const rows = extractRows(await upstream.arrayBuffer()); return { fetched_at: new Date().toISOString(), source: 'FCC LMS Current_LMS_Dump.zip', all: rows, radio: rows.filter(row => matchesService(row, 'radio')), television: rows.filter(row => matchesService(row, 'television')) }; }
async function cacheDataset(env, dataset) { if (!env.FCC_CACHE) return; await Promise.all(['all', 'radio', 'television'].map(service => env.FCC_CACHE.put(`${CACHE_PREFIX}${service}`, JSON.stringify({ data: dataset[service], connected: true, service, source: dataset.source, fetched_at: dataset.fetched_at, review_count: dataset[service].filter(row => row.review).length }), { expirationTtl: 172800 }))); }
async function responseFromCache(env, service) { if (!env.FCC_CACHE) return null; const cached = await env.FCC_CACHE.get(`${CACHE_PREFIX}${service}`, 'json'); return cached ? Response.json(cached, { headers: { 'Cache-Control': 'public, max-age=900' } }) : null; }
export default { async fetch(request, env) { const url = new URL(request.url); if (url.pathname !== '/api/fcc/transactions') return new Response('Not found', { status: 404 }); if (request.method !== 'GET') return new Response('Method not allowed', { status: 405 }); const requested = url.searchParams.get('service'); const service = ['radio', 'television', 'all'].includes(requested) ? requested : 'radio'; try { const cached = await responseFromCache(env, service); if (cached) return cached; const dataset = await fetchDataset(); await cacheDataset(env, dataset); const rows = dataset[service]; return Response.json({ data: rows, connected: true, service, source: dataset.source, fetched_at: dataset.fetched_at, review_count: rows.filter(row => row.review).length }, { headers: { 'Cache-Control': 'public, max-age=900' } }); } catch (error) { return Response.json({ data: [], connected: false, service, error: error.message }, { status: 502 }); } }, async scheduled(controller, env) { try { const dataset = await fetchDataset(); await cacheDataset(env, dataset); console.log(`FCC refresh completed at ${dataset.fetched_at}`); } catch (error) { console.error(`FCC refresh failed: ${error.message}`); } } };
