name = "mjr-fcc-management"
main = "fcc_transactions_worker.js"
compatibility_date = "2026-10-09"
workers_dev = true

[triggers]
crons = ["30 6 * * *"]

[[kv_namespaces]]
binding = "FCC_CACHE"
id = "4c757ac88ca84cf78271cdb8cc7242d1"

[vars]
FCC_LMS_TRANSACTIONS_URL = "https://enterpriseefiling.fcc.gov/dataentry/api/download/dbfile/Current_LMS_Dump.zip"
