import { unzipSync, strFromU8 } from 'fflate';
import { writeFile } from 'node:fs/promises';

const source = 'https://enterpriseefiling.fcc.gov/dataentry/api/download/dbfile/Current_LMS_Dump.zip';
const aliases = { call: ['callsign','call sign','station','station callsign','call_sign'], city: ['city','community','station city','community of license'], state: ['state','state code','state abbreviation'], service: ['service','service code','facility type','service type','app service'], file: ['file number','filenumber','application number','app number','id','file_no','application id'], type: ['purpose','transaction type','application purpose','form','application type','purpose description'], seller: ['assignor','seller','transferor','licensee'], buyer: ['assignee','buyer','transferee','applicant'], status: ['status','application status','status description'], filed: ['date filed','filed date','filing date','received date'], statusDate: ['status date','action date','date status','grant date','last action date'] };
const key = value => String(value ?? '').trim().toLowerCase().replace(/[^a-z0-9]/g, '');
const getValue = (row, names) => { const found = Object.keys(row).find(k => names.map(key).includes(key(k))); return found ? String(row[found] ?? '').trim() : ''; };
function normalize(row, file) { const record = Object.fromEntries(Object.entries(aliases).map(([name, names]) => [name, getValue(row, names)])); record.source_file = file; record.review = !record.file || !record.call || !record.status || !record.statusDate; record.isTransaction = /assign|transfer|sale|control|renew|modif|permit|license|application|ownership/i.test(`${record.type} ${record.status}`); return record; }
function splitLine(line, delimiter) { const cells = []; let cell = '', quoted = false; for (let i=0; i<line.length; i++) { const c=line[i], next=line[i+1]; if (c==='"' && quoted && next==='"') { cell+='"'; i++; continue; } if (c==='"') { quoted=!quoted; continue; } if (c===delimiter && !quoted) { cells.push(cell); cell=''; continue; } cell+=c; } cells.push(cell); return cells; }
function parse(text, file) { const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(line=>line.trim()); if(lines.length<2)return[]; const delimiter=lines[0].includes('|')?'|':(lines[0].includes('\t')?'\t':','); const headers=splitLine(lines[0],delimiter).map(x=>x.trim()); if(!headers.some(x=>/call|station|file|status|purpose|service/i.test(x)))return[]; return lines.slice(1).map(line=>{const cells=splitLine(line,delimiter); return normalize(Object.fromEntries(headers.map((h,i)=>[h,cells[i]??''])),file);}); }
function serviceMatches(row, service) { if(service==='all')return true; const text=row.service.toLowerCase(); return service==='television'?/tv|television|class ?a|lptv|dtv/.test(text):/am|fm|radio|translator|lpfm/.test(text); }
const response=await fetch(source,{headers:{'User-Agent':'MJR FCC Management/1.0 (+https://mediajobsreport.com)',Accept:'application/zip'}}); if(!response.ok)throw new Error(`FCC LMS source returned HTTP ${response.status}`);
const files=unzipSync(new Uint8Array(await response.arrayBuffer())); const all=[]; const seen=new Set(); const debug=[];
for(const [name,bytes] of Object.entries(files)){const excluded=/\/|^_|readme|code.?table|schema/i.test(name); const probe=strFromU8(bytes.slice(0,Math.min(bytes.length,200000))); const firstLine=probe.split(/\r?\n/).find(line=>line.trim())||''; debug.push({name,size:bytes.length,firstLine:firstLine.slice(0,500)}); if(excluded||bytes.length>80000000||/\0/.test(text.slice(0,2000)))continue; for(const row of parse(text,name)){if(!row.isTransaction)continue; const identity=`${row.file}|${row.call}|${row.statusDate}|${row.type}`; if(seen.has(identity))continue; seen.add(identity); all.push(row);}}
const fetched_at=new Date().toISOString(); for(const service of ['all','radio','television']){const data=all.filter(row=>serviceMatches(row,service)); await writeFile(`cache-${service}.json`,JSON.stringify({data,connected:true,service,source:'FCC LMS Current_LMS_Dump.zip',fetched_at,review_count:data.filter(row=>row.review).length}));} await writeFile('cache-debug.json',JSON.stringify({fetched_at,files:debug})); console.log(JSON.stringify({fetched_at,records:all.length,radio:all.filter(r=>serviceMatches(r,'radio')).length,television:all.filter(r=>serviceMatches(r,'television')).length}));
